lazy-loading-in-html-images
atapas/html-tips-tricks pull request #10
Opened 2022-10-04 07:38 UTC by Alidhuniya

2022-10-05 02:35 UTC, atapas commented
@Alidhuniya Which issue is it related to? Please provide the issue link here.

2022-10-05 04:54 UTC, Alidhuniya commented
> @Alidhuniya Which issue is it related to? Please provide the issue link here.

sorry, you don't have contribution guide. Here is the issue link. Issue No, (#18)

2022-10-05 10:47 UTC, atapas reviewed
@Alidhuniya You got to modify the main index file to link this demo.

2022-10-06 05:30 UTC, Alidhuniya commented
> @Alidhuniya You got to modify the main index file to link this demo.

it's linked now

2022-10-06 06:28 UTC, atapas requested changes
Please correct the typo.

2022-10-06 06:28 UTC, atapas commented on lazy-loading/index.html
> +    <h2>Open Network tab and scroll at the same time t see effect</h2>
@Alidhuniya Typo

<img width="442" alt="image" src="https://user-images.githubusercontent.com/3633137/194230191-9c174c2b-a5b5-443e-91ed-a526d7659d78.png">

2022-10-06 07:30 UTC, Alidhuniya commented on lazy-loading/index.html
> +    <h2>Open Network tab and scroll at the same time t see effect</h2>
> 

fixed..have a look at

2022-10-06 18:05 UTC, atapas approved these changes
@Alidhuniya Thanks for your contribution. Looks good.

2022-10-06 18:05 UTC, merged